[setup_common]
CompanyName = TC-HELICON
ProductName = USB Audio Driver for Blender
ProductVersion = 4.38.0
DefaultInstDir = TC-HELICON\Blender_Audio_Driver
SetupRegPath = TC-HELICON\blender_audio\Setup
CopyFiles = thesycon.ico
ShowLicenseText = 0
UseCustomizedBitmap = 1
CustomUninstallIcon = thesycon.ico
CertificateFile = vendor.cer
SupportURL = http://www.music-group.com

[setup_x86.package_1]
SupportedOS = 7, 8, 8.1
SubDir = W7W8_x86
CopyFiles = custom.ini, blender_audio.cat, blender_audio.sys, blender_audioks.cat, blender_audioks.sys, BlenderAudioCplApp.xml, BlenderAudioCplApp.strings\en.txt, BlenderAudioCplApp.strings\de.txt
InfUSB = blender_audio.inf
InfKS = blender_audioks.inf
RegisterFiles = blender_audioapi.dll, blender_audioasio.dll
ControlPanelExe = BlenderAudioCplApp.exe
CheckCodeIntegrity = blender_audio.sys
ShortCut1 = $SM_PROG_ALL_USERS|TC-HELICON\USB Audio Driver for Blender|Blender Control Panel.lnk|$INSTDIR\W7W8_x86\BlenderAudioCplApp.exe||
ShortCut2 = $SM_STARTUP_ALL_USERS||Blender Control Panel Autostart.lnk|$INSTDIR\W7W8_x86\BlenderAudioCplApp.exe|-hide|

[setup_x64.package_1]
SupportedOS = 7, Server2008R2, HomeServer2011, 8, Server2012, 8.1, Server2012R2
SubDir = W7W8_x64
CopyFiles = custom.ini, blender_audio.cat, blender_audio.sys, blender_audioks.cat, blender_audioks.sys, BlenderAudioCplApp.xml, BlenderAudioCplApp.strings\en.txt, BlenderAudioCplApp.strings\de.txt
InfUSB = blender_audio.inf
InfKS = blender_audioks.inf
RegisterFiles = blender_audioapi.dll, blender_audioapi_x64.dll, blender_audioasio.dll, blender_audioasio_x64.dll
ControlPanelExe = BlenderAudioCplApp.exe
CheckCodeIntegrity = blender_audio.sys
ShortCut1 = $SM_PROG_ALL_USERS|TC-HELICON\USB Audio Driver for Blender|Blender Control Panel.lnk|$INSTDIR\W7W8_x64\BlenderAudioCplApp.exe||
ShortCut2 = $SM_STARTUP_ALL_USERS||Blender Control Panel Autostart.lnk|$INSTDIR\W7W8_x64\BlenderAudioCplApp.exe|-hide|

[setup_x86.package_2]
SupportedOS = 10
SubDir = W10_x86
CopyFiles = custom.ini, blender_audio.cat, blender_audio.sys, blender_audioks.cat, blender_audioks.sys, BlenderAudioCplApp.xml, BlenderAudioCplApp.strings\en.txt, BlenderAudioCplApp.strings\de.txt
InfUSB = blender_audio.inf
InfKS = blender_audioks.inf
RegisterFiles = blender_audioapi.dll, blender_audioasio.dll
ControlPanelExe = BlenderAudioCplApp.exe
CheckCodeIntegrity = blender_audio.sys
ShortCut1 = $SM_PROG_ALL_USERS|TC-HELICON\USB Audio Driver for Blender|Blender Control Panel.lnk|$INSTDIR\W10_x86\BlenderAudioCplApp.exe||
ShortCut2 = $SM_STARTUP_ALL_USERS||Blender Control Panel Autostart.lnk|$INSTDIR\W10_x86\BlenderAudioCplApp.exe|-hide|

[setup_x64.package_2]
SupportedOS = 10, Server2016
SubDir = W10_x64
CopyFiles = custom.ini, blender_audio.cat, blender_audio.sys, blender_audioks.cat, blender_audioks.sys, BlenderAudioCplApp.xml, BlenderAudioCplApp.strings\en.txt, BlenderAudioCplApp.strings\de.txt
InfUSB = blender_audio.inf
InfKS = blender_audioks.inf
RegisterFiles = blender_audioapi.dll, blender_audioapi_x64.dll, blender_audioasio.dll, blender_audioasio_x64.dll
ControlPanelExe = BlenderAudioCplApp.exe
CheckCodeIntegrity = blender_audio.sys
ShortCut1 = $SM_PROG_ALL_USERS|TC-HELICON\USB Audio Driver for Blender|Blender Control Panel.lnk|$INSTDIR\W10_x64\BlenderAudioCplApp.exe||
ShortCut2 = $SM_STARTUP_ALL_USERS||Blender Control Panel Autostart.lnk|$INSTDIR\W10_x64\BlenderAudioCplApp.exe|-hide|

